#############
### build ###
#############

# base image
FROM node:16 as build

# set working directory
WORKDIR /app

# install and cache app dependencies
COPY ./package*.json ./
RUN npm install

# add app
COPY . .

# generate build
RUN npm run build

############
### prod ###
############

# base image
FROM nginx:1.19.6-alpine
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/dist/frontend/ /usr/share/nginx/html