version: "3.3"

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    depends_on:
      - frontend
    restart: always # because it is routing traffic to our entire app
    ports:
      - 80:80
      - 443:443
    volumes:
      - $PWD/nginx/data/certs/prod:/etc/nginx/certs
      - $PWD/nginx/configs/prod/upstream.conf:/etc/nginx/conf.d/upstream.conf
    networks:
      - pf-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - '8080:80'
    volumes:
      - ./frontend:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules
    networks:
      - pf-network

networks:
  pf-network:
    driver: bridge
